#/* -----------------------------------------------------------------------------

#FILE NAME:         Makefile
#DESCRIPTION:       Makefile for a C++ program
#USAGE:             Target .cpp files. Build a program executable on Linux
#COMPILER:			Makefile. Builds cpp files using g++
#NOTES:

#MODIFICATION HISTORY:

#Author             Date           Modification(s)
#----------------   -----------    ---------------
#Albert Galang      2019-02-19     1.0: In-class code
#Albert Galang      2019-02-19     1.1: Added comment headers
#Albert Galang      2019-02-26     1.2: Added compilation settings to include
#										changes in header files
#Albert Galang      2019-03-04     1.3: Updated comment headers

#----------------------------------------------------------------------------- */
.cpp :
	g++ -o $* $*.cpp -std=c++11


# This will build the executable that have dependencies on .h files
#cust_ports_v1 : cust_ports_v1.h
