# ---------------------------------------------------------------------------------------
# FILE NAME:         Makefile
# DESCRIPTION:
# USAGE:             make
# COMPILER:          GNU g++ compiler on Linux
#
# MODIFICATION HISTORY:
# Author               Date            Version             Description
# ---------------      ----------      ------------        ------------
# Luiz Diego Garcia    02/18/19        0.0.1               Created File
# Luiz Diego Garcia    02/26/19        0.0.2               Changed to Makefile2
# Luiz Diego Garcia    03/01/19        0.0.3               Added cust_ports_v1 header file 
# Luiz Diego Garcia    03/01/19        0.0.4               Added cust_ports header file 
# Luiz Diego Garcia    03/01/19        1.0.0               Deleted unused stuff 
# ---------------------------------------------------------------------------------------

.cpp :
	g++ -o $* $*.cpp -std=c++11

cust_ports			: cust_ports.h